In [30]:
import yfinance as yf
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, Column, String, Date, Numeric, MetaData, Table

tickerName = yf.Ticker("MSFT") #MSFT #OLAELEC.NS
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [2]:
#HOME_PC_DB

engine = create_engine(
    "postgresql+psycopg2://postgres:123456@localhost:5432/postgres"
)

In [3]:

dfIncomeStatementQ = tickerName.get_income_stmt(as_dict=False, pretty=False, freq="quarterly")
dfIncomeStatementY = tickerName.get_income_stmt(as_dict=False, pretty=False, freq="yearly")

In [4]:


ittelson_income_statement_columns = [
    'TotalRevenue', 
    'CostOfRevenue', 
    'GrossProfit',
    'OperatingExpense',
    'OperatingIncome',
    'NetInterestIncome',
    'TaxProvision',
    'NetIncome'
]

dfIncomeStatementQ = pd.DataFrame(dfIncomeStatementQ)
clean_quarterly_income_statement = dfIncomeStatementQ.loc[ittelson_income_statement_columns]
display(clean_quarterly_income_statement.transpose())

dfIncomeStatementY = pd.DataFrame(dfIncomeStatementY)
clean_yearly_income_statement = dfIncomeStatementY.loc[ittelson_income_statement_columns]
display(clean_yearly_income_statement.transpose())

,TotalRevenue,CostOfRevenue,GrossProfit,OperatingExpense,OperatingIncome,NetInterestIncome,TaxProvision,NetIncome
2025-12-31,4700000000.00,3090000000.00,1610000000.00,6020000000.00,-4410000000.00,-800000000.00,0.00,-4870000000.00
2025-06-30,8280000000.00,6140000000.00,2140000000.00,6160000000.00,-4020000000.00,-940000000.00,0.00,-4280000000.00
2025-03-31,950000000.00,5650000000.00,-4700000000.00,3230000000.00,-7930000000.00,1410000000.00,0.00,-8700000000.00
2024-12-31,10450000000.00,8510000000.00,1940000000.00,7920000000.00,-5980000000.00,-930000000.00,0.00,-5640000000.00
2024-09-30,12140000000.00,9890000000.00,2250000000.00,7360000000.00,-5110000000.00,-840000000.00,0.00,-4950000000.00

,TotalRevenue,CostOfRevenue,GrossProfit,OperatingExpense,OperatingIncome,NetInterestIncome,TaxProvision,NetIncome
2025-03-31,39980000000.00,37460000000.00,2520000000.00,24850000000.00,-22330000000.00,-1030000000.00,0.00,-22760000000.00
2024-03-31,47980000000.00,44110000000.00,3870000000.00,19550000000.00,-15680000000.00,-880000000.00,0.00,-15840000000.00
2023-03-31,26004760000.00,25899730000.00,105030000.00,14028160000.00,-13923130000.00,-84110000.00,0.00,-14720790000.00
2022-03-31,3679930000.00,4887180000.00,-1207250000.00,6959100000.00,-8166350000.00,402840000.00,0.00,-7841500000.00

In [5]:


dfIncomeStatementQ = clean_quarterly_income_statement.T.reset_index()
dfIncomeStatementQ_sql = dfIncomeStatementQ.rename(columns={'index': 'ReportDate'})
dfIncomeStatementQ_sql.insert(1,'Ticker',tickerName.ticker)
display(dfIncomeStatementQ)


dfIncomeStatementY = clean_yearly_income_statement.T.reset_index()
dfIncomeStatementY_sql = dfIncomeStatementY.rename(columns={'index': 'ReportDate'})
dfIncomeStatementY_sql.insert(1,'Ticker',tickerName.ticker)
display(dfIncomeStatementY)

,index,TotalRevenue,CostOfRevenue,GrossProfit,OperatingExpense,OperatingIncome,NetInterestIncome,TaxProvision,NetIncome
0,2025-12-31,4700000000.00,3090000000.00,1610000000.00,6020000000.00,-4410000000.00,-800000000.00,0.00,-4870000000.00
1,2025-06-30,8280000000.00,6140000000.00,2140000000.00,6160000000.00,-4020000000.00,-940000000.00,0.00,-4280000000.00
2,2025-03-31,950000000.00,5650000000.00,-4700000000.00,3230000000.00,-7930000000.00,1410000000.00,0.00,-8700000000.00
3,2024-12-31,10450000000.00,8510000000.00,1940000000.00,7920000000.00,-5980000000.00,-930000000.00,0.00,-5640000000.00
4,2024-09-30,12140000000.00,9890000000.00,2250000000.00,7360000000.00,-5110000000.00,-840000000.00,0.00,-4950000000.00

,index,TotalRevenue,CostOfRevenue,GrossProfit,OperatingExpense,OperatingIncome,NetInterestIncome,TaxProvision,NetIncome
0,2025-03-31,39980000000.00,37460000000.00,2520000000.00,24850000000.00,-22330000000.00,-1030000000.00,0.00,-22760000000.00
1,2024-03-31,47980000000.00,44110000000.00,3870000000.00,19550000000.00,-15680000000.00,-880000000.00,0.00,-15840000000.00
2,2023-03-31,26004760000.00,25899730000.00,105030000.00,14028160000.00,-13923130000.00,-84110000.00,0.00,-14720790000.00
3,2022-03-31,3679930000.00,4887180000.00,-1207250000.00,6959100000.00,-8166350000.00,402840000.00,0.00,-7841500000.00

In [6]:

metadata = MetaData(schema='public')

#Define the architecture
quarterly_income_statement = Table(
    'quarterly_income_statement', metadata,
    Column('Ticker', String(10), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('TotalRevenue', Numeric),
    Column('CostOfRevenue', Numeric),
    Column('GrossProfit', Numeric),
    Column('OperatingExpense', Numeric),
    Column('OperatingIncome', Numeric),
    Column('NetInterestIncome', Numeric),
    Column('TaxProvision', Numeric),
    Column('NetIncome', Numeric)
)
#Define the architecture
yearly_income_statement = Table(
    'yearly_income_statement', metadata,
    Column('Ticker', String(10), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('TotalRevenue', Numeric),
    Column('CostOfRevenue', Numeric),
    Column('GrossProfit', Numeric),
    Column('OperatingExpense', Numeric),
    Column('OperatingIncome', Numeric),
    Column('NetInterestIncome', Numeric),
    Column('TaxProvision', Numeric),
    Column('NetIncome', Numeric)
)

#Build the table in the database
metadata.create_all(engine)
print("Tables created successfully.")

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [7]:
#Insert DataFrames to Tables

import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.dialects.postgresql import insert

#Define the Custom Upsert Logic
def postgres_upsert(table, conn, keys, data_iter):
    """
    Native PostgreSQL UPSERT
    """
    # Convert Pandas data into a list of dictionaries
    data = [dict(zip(keys, row)) for row in data_iter]
    
    insert_stmt = insert(table.table).values(data)

    update_dict = {
    c.name: getattr(insert_stmt.excluded, c.name)
    for c in table.table.columns
    if c.name not in ("Ticker", "ReportDate")
}
    
    upsert_stmt = insert_stmt.on_conflict_do_update(
        index_elements=['Ticker', 'ReportDate'], 
        set_=update_dict
    )
    
    conn.execute(upsert_stmt)


# Push the data using the custom Upsert method
dfIncomeStatementQ_sql.to_sql(
    name='quarterly_income_statement',
    con=engine,
    schema='public',
    if_exists='append',
    index=False,
    method=postgres_upsert
)

dfIncomeStatementY_sql.to_sql(
    name='yearly_income_statement',
    con=engine,
    schema='public',
    if_exists='append',
    index=False,
    method=postgres_upsert
)

print("Data successfully upserted into the database.")

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [32]:
dfBalanceSheetQ = tickerName.get_balance_sheet(as_dict=False, pretty=False, freq="quarterly")
dfBalanceSheetY = tickerName.get_balance_sheet(as_dict=False, pretty=False, freq="yearly")

In [ ]:
dfBalanceSheetQ = pd.DataFrame(dfBalanceSheetQ)
masterRec = dfBalanceSheetQ.loc['Receivables']
masterRec

0

In [ ]:
ittelson_balance_sheet_columns = [
  #Assets
  'CashCashEquivalentsAndShortTermInvestments',
  'Receivables',
  'Inventory',
  'CurrentAssets',
  'TotalNonCurrentAssets',
  'GrossPPE',
  'AccumulatedDepreciation',
  'NetPPE',
  'TotalAssets',
  #Liabilities&Equity
  'PayablesAndAccruedExpenses',
  'CurrentDebtAndCapitalLeaseObligation',
  'TotalTaxPayable',
  'CurrentLiabilities',
  'LongTermDebtAndCapitalLeaseObligation',
  'TotalLiabilitiesNetMinorityInterest', #Current Liabilities + Long-Term Debt.
  'CapitalStock',
  'RetainedEarnings',
  'StockholdersEquity'
]