In [192]:
import yfinance as yf
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, Column, String, Date, Numeric, MetaData, Table

tickerName = yf.Ticker("MSFT") #MSFT #OLAELEC.NS
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [193]:
dfq = tickerName.get_income_stmt(as_dict=False, pretty=False, freq="quarterly")

In [194]:
dfy = tickerName.get_income_stmt(as_dict=False, pretty=False, freq="yearly")

In [195]:
#HOME_PC_DB

engine = create_engine(
    "postgresql+psycopg2://postgres:123456@localhost:5432/postgres"
)

In [196]:


ittelson_columns = [
    'TotalRevenue', 
    'CostOfRevenue', 
    'GrossProfit',
    'OperatingExpense',
    'OperatingIncome',
    'NetInterestIncome',
    'TaxProvision',
    'NetIncome'
]

dfq = pd.DataFrame(dfq)
clean_quarterly_income_statement = dfq.loc[ittelson_columns]
display(clean_quarterly_income_statement.transpose())

dfy = pd.DataFrame(dfy)
clean_yearly_income_statement = dfy.loc[ittelson_columns]
display(clean_yearly_income_statement.transpose())

,TotalRevenue,CostOfRevenue,GrossProfit,OperatingExpense,OperatingIncome,NetInterestIncome,TaxProvision,NetIncome
2025-12-31,81273000000.00,25978000000.00,55295000000.00,17020000000.00,38275000000.00,104000000.00,9788000000.00,38458000000.00
2025-09-30,77673000000.00,24043000000.00,53630000000.00,15669000000.00,37961000000.00,278000000.00,6554000000.00,27747000000.00
2025-06-30,76441000000.00,24014000000.00,52427000000.00,18104000000.00,34323000000.00,154000000.00,5383000000.00,27233000000.00
2025-03-31,70066000000.00,21919000000.00,48147000000.00,16147000000.00,32000000000.00,3000000.00,5553000000.00,25824000000.00
2024-12-31,69632000000.00,21799000000.00,47833000000.00,16180000000.00,31653000000.00,6000000.00,5257000000.00,24108000000.00

,TotalRevenue,CostOfRevenue,GrossProfit,OperatingExpense,OperatingIncome,NetInterestIncome,TaxProvision,NetIncome
2025-06-30,281724000000.00,87831000000.00,193893000000.00,65365000000.00,128528000000.00,262000000.00,21795000000.00,101832000000.00
2024-06-30,245122000000.00,74114000000.00,171008000000.00,61575000000.00,109433000000.00,222000000.00,19651000000.00,88136000000.00
2023-06-30,211915000000.00,65863000000.00,146052000000.00,57529000000.00,88523000000.00,1026000000.00,16950000000.00,72361000000.00
2022-06-30,198270000000.00,62650000000.00,135620000000.00,52237000000.00,83383000000.00,31000000.00,10978000000.00,72738000000.00

In [197]:


dfq = clean_quarterly_income_statement.T.reset_index()
dfq_sql = dfq.rename(columns={'index': 'ReportDate'})
dfq_sql.insert(1,'Ticker',tickerName.ticker)
display(dfq_sql)


dfy = clean_yearly_income_statement.T.reset_index()
dfy_sql = dfy.rename(columns={'index': 'ReportDate'})
dfy_sql.insert(1,'Ticker',tickerName.ticker)
display(dfy_sql)

,ReportDate,Ticker,TotalRevenue,CostOfRevenue,GrossProfit,OperatingExpense,OperatingIncome,NetInterestIncome,TaxProvision,NetIncome
0,2025-12-31,MSFT,81273000000.00,25978000000.00,55295000000.00,17020000000.00,38275000000.00,104000000.00,9788000000.00,38458000000.00
1,2025-09-30,MSFT,77673000000.00,24043000000.00,53630000000.00,15669000000.00,37961000000.00,278000000.00,6554000000.00,27747000000.00
2,2025-06-30,MSFT,76441000000.00,24014000000.00,52427000000.00,18104000000.00,34323000000.00,154000000.00,5383000000.00,27233000000.00
3,2025-03-31,MSFT,70066000000.00,21919000000.00,48147000000.00,16147000000.00,32000000000.00,3000000.00,5553000000.00,25824000000.00
4,2024-12-31,MSFT,69632000000.00,21799000000.00,47833000000.00,16180000000.00,31653000000.00,6000000.00,5257000000.00,24108000000.00

,ReportDate,Ticker,TotalRevenue,CostOfRevenue,GrossProfit,OperatingExpense,OperatingIncome,NetInterestIncome,TaxProvision,NetIncome
0,2025-06-30,MSFT,281724000000.00,87831000000.00,193893000000.00,65365000000.00,128528000000.00,262000000.00,21795000000.00,101832000000.00
1,2024-06-30,MSFT,245122000000.00,74114000000.00,171008000000.00,61575000000.00,109433000000.00,222000000.00,19651000000.00,88136000000.00
2,2023-06-30,MSFT,211915000000.00,65863000000.00,146052000000.00,57529000000.00,88523000000.00,1026000000.00,16950000000.00,72361000000.00
3,2022-06-30,MSFT,198270000000.00,62650000000.00,135620000000.00,52237000000.00,83383000000.00,31000000.00,10978000000.00,72738000000.00

In [198]:

metadata = MetaData(schema='public')

#Define the architecture
quarterly_income_statement = Table(
    'quarterly_income_statement', metadata,
    Column('Ticker', String(10), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('TotalRevenue', Numeric),
    Column('CostOfRevenue', Numeric),
    Column('GrossProfit', Numeric),
    Column('OperatingExpense', Numeric),
    Column('OperatingIncome', Numeric),
    Column('NetInterestIncome', Numeric),
    Column('TaxProvision', Numeric),
    Column('NetIncome', Numeric)
)
#Define the architecture
yearly_income_statement = Table(
    'yearly_income_statement', metadata,
    Column('Ticker', String(10), primary_key=True),
    Column('ReportDate', Date, primary_key=True),
    Column('TotalRevenue', Numeric),
    Column('CostOfRevenue', Numeric),
    Column('GrossProfit', Numeric),
    Column('OperatingExpense', Numeric),
    Column('OperatingIncome', Numeric),
    Column('NetInterestIncome', Numeric),
    Column('TaxProvision', Numeric),
    Column('NetIncome', Numeric)
)

#Build the table in the database
metadata.create_all(engine)
print("Tables created successfully.")

Tables created successfully.

In [199]:
#Insert DataFrames to Tables

import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.dialects.postgresql import insert

#Define the Custom Upsert Logic
def postgres_upsert(table, conn, keys, data_iter):
    """
    Native PostgreSQL UPSERT
    """
    # Convert Pandas data into a list of dictionaries
    data = [dict(zip(keys, row)) for row in data_iter]
    
    insert_stmt = insert(table.table).values(data)

    update_dict = {
    c.name: getattr(insert_stmt.excluded, c.name)
    for c in table.table.columns
    if c.name not in ("Ticker", "ReportDate")
}
    
    upsert_stmt = insert_stmt.on_conflict_do_update(
        index_elements=['Ticker', 'ReportDate'], 
        set_=update_dict
    )
    
    conn.execute(upsert_stmt)


# Push the data using the custom Upsert method
dfq_sql.to_sql(
    name='quarterly_income_statement',
    con=engine,
    schema='public',
    if_exists='append',
    index=False,
    method=postgres_upsert
)

dfy_sql.to_sql(
    name='yearly_income_statement',
    con=engine,
    schema='public',
    if_exists='append',
    index=False,
    method=postgres_upsert
)

print("Data successfully upserted into the database.")

Data successfully upserted into the database.